# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://zzgdream.github.io
date_format: "ordinal"
title: zzgdream's-blog
subtitle: "敲着代码看世界的散人"
description: "zzgdream的个人博客"
keywords: zzgdream,linghucong,Python,Spider,Django,Flask
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: zzgdream
# organization: www.jianshu.com/u/bf4c0b4a8c83
# organization_url: https://www.jianshu.com/u/bf4c0b4a8c83
github_username: zzgdream
location: BeiJing, China
email: 1030038593@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  #-
    #href: /https://www.jianshu.com/u/bf4c0b4a8c83
    #label: 简书
#
  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: ZZGDream/ZZGDream.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
